import { useCallback, useEffect, useRef, useState } from 'react';
import type { FxState } from '../core/fxState';
type Recognition={lang:string;interimResults:boolean;continuous:boolean;maxAlternatives:number;onstart:null|(()=>void);onresult:null|((e:any)=>void);onerror:null|((e:any)=>void);onend:null|(()=>void);start:()=>void;abort:()=>void};
export function useFxVoice(){
 const [state,setState]=useState<FxState>('idle');const [transcript,setTranscript]=useState('');const [error,setError]=useState('');const recognition=useRef<Recognition|null>(null);const utterance=useRef<SpeechSynthesisUtterance|null>(null);
 useEffect(()=>()=>{recognition.current?.abort();window.speechSynthesis?.cancel();},[]);
 const listen=useCallback(()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setError('speech-recognition-unsupported');setState('error');return;}window.speechSynthesis?.cancel();setTranscript('');setError('');recognition.current?.abort();const r:Recognition=new SR();recognition.current=r;r.lang='es-MX';r.interimResults=false;r.continuous=false;r.maxAlternatives=1;r.onstart=()=>setState('listening');r.onresult=(e:any)=>{setTranscript(e.results[0][0].transcript);setState('processing');};r.onerror=(e:any)=>{if(e.error==='no-speech'||e.error==='aborted'){setState('idle');return;}setError(e.error||'voice-error');setState('error');};r.onend=()=>setState(s=>s==='listening'?'idle':s);r.start();},[]);
 const speak=useCallback((text:string)=>{if(!('speechSynthesis'in window)){setError('speech-synthesis-unsupported');setState('error');return;}recognition.current?.abort();window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);utterance.current=u;u.lang='es-MX';u.rate=.94;u.pitch=.88;u.volume=1;const voices=window.speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang.toLowerCase()==='es-mx')||voices.find(v=>v.lang.toLowerCase().startsWith('es'))||null;u.onstart=()=>setState('speaking');u.onend=()=>{utterance.current=null;setState('idle');};u.onerror=(e:any)=>{utterance.current=null;if(e.error==='interrupted'||e.error==='canceled'){setState('idle');return;}setError(e.error||'speech-error');setState('error');};window.speechSynthesis.resume();window.speechSynthesis.speak(u);},[]);
 const reset=useCallback(()=>{setTranscript('');setError('');},[]);const stop=useCallback(()=>{recognition.current?.abort();window.speechSynthesis?.cancel();setState('idle');},[]);
 return {state,transcript,error,listen,speak,reset,stop,setState};
}
