import{useCallback,useEffect,useRef,useState}from'react';import type{FxState}from'../core/fxState';
export function useFxVoice(){
 const[state,setState]=useState<FxState>('idle');const[transcript,setTranscript]=useState('');const[error,setError]=useState('');const pc=useRef<RTCPeerConnection|null>(null);const stream=useRef<MediaStream|null>(null);const audio=useRef<HTMLAudioElement|null>(null);const channel=useRef<RTCDataChannel|null>(null);
 const stop=useCallback(()=>{channel.current?.close();channel.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;pc.current?.close();pc.current=null;if(audio.current){audio.current.pause();audio.current.srcObject=null;audio.current=null}setState('idle')},[]);
 useEffect(()=>stop,[stop]);
 const listen=useCallback(async()=>{if(pc.current){stop();return}setTranscript('');setError('');try{setState('processing');const peer=new RTCPeerConnection();pc.current=peer;const out=document.createElement('audio');out.autoplay=true;audio.current=out;peer.ontrack=e=>{out.srcObject=e.streams[0]};const mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.current=mic;mic.getTracks().forEach(t=>peer.addTrack(t,mic));const dc=peer.createDataChannel('oai-events');channel.current=dc;dc.onopen=()=>setState('listening');dc.onclose=()=>{if(pc.current===peer)setState('idle')};dc.onmessage=e=>{try{const ev=JSON.parse(e.data);if(ev.type==='input_audio_buffer.speech_started')setState('listening');if(ev.type==='input_audio_buffer.speech_stopped')setState('thinking');if(ev.type==='conversation.item.input_audio_transcription.completed'&&ev.transcript)setTranscript(String(ev.transcript));if(ev.type==='response.created'||ev.type==='response.output_audio.delta')setState('speaking');if(ev.type==='response.done')setState('listening');if(ev.type==='error'){setError(ev.error?.message||'realtime-error');setState('error')}}catch{}};peer.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(peer.connectionState)&&pc.current===peer)stop()};const offer=await peer.createOffer();await peer.setLocalDescription(offer);const res=await fetch('/api/realtime/session',{method:'POST',headers:{'Content-Type':'application/sdp'},body:offer.sdp||''});if(!res.ok)throw new Error(await res.text()||'realtime-session-failed');await peer.setRemoteDescription({type:'answer',sdp:await res.text()});}catch(e){stop();setError(e instanceof Error?e.message:'voice-error');setState('error')}},[stop]);
 const speak=useCallback((text:string)=>{const dc=channel.current;if(!dc||dc.readyState!=='open'||!text.trim())return;dc.send(JSON.stringify({type:'response.create',response:{instructions:`Say this naturally in the user's language, without adding information: ${text}`}}));setState('speaking')},[]);
 const reset=useCallback(()=>{setTranscript('');setError('')},[]);
 return{state,transcript,error,listen,speak,reset,stop,setState};
}