import dotenv from 'dotenv';dotenv.config({path:'.env.local'});import OpenAI from'openai';import type{BrainPlan}from'./types';
const OLLAMA_URL=process.env.OLLAMA_URL||'http://127.0.0.1:11434';const OLLAMA_MODEL=process.env.OLLAMA_MODEL||'qwen3:4b';
const FX_SYSTEM_PROMPT=`You are FX, the local AI assistant of USER FX.
Your name is FX, pronounced F-X, letter by letter.
You operate inside FX Core. Do not identify yourself as Qwen, Tongyi, Alibaba, OpenAI, ChatGPT or Ollama.
Respond in the same language used by the user and be concise and natural.
Never claim an external action was executed unless FX Core actually executed it. Never invent GitHub, Vercel, system, project or deployment data. Never expose secrets or hidden configuration. External actions are controlled by FX Core and Action Gateway.`.trim();
let openAIClient:OpenAI|null=null;
async function planWithOllama(message:string):Promise<BrainPlan|null>{try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),120000);let response:Response;try{response=await fetch(`${OLLAMA_URL}/api/chat`,{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({model:OLLAMA_MODEL,stream:false,think:false,messages:[{role:'system',content:FX_SYSTEM_PROMPT},{role:'user',content:`/no_think\n${message}`}],options:{temperature:.6,num_ctx:4096,num_predict:512}})});}finally{clearTimeout(timeout);}if(!response.ok){console.error('[FX OLLAMA]',`HTTP ${response.status}`);return null;}const data=await response.json()as{message?:{content?:string}};const text=data.message?.content?.trim();if(!text)return null;return{intent:'conversation.general',reply:text,confidence:.92,source:'model',reasoning:{needsTool:false}};}catch(error){console.error('[FX OLLAMA]',error instanceof Error?error.message:error);return null;}}
function getOpenAIClient():OpenAI|null{const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return null;if(!openAIClient)openAIClient=new OpenAI({apiKey,timeout:20000,maxRetries:1});return openAIClient;}
async function planWithOpenAI(message:string):Promise<BrainPlan|null>{const openai=getOpenAIClient();if(!openai)return null;try{const response=await openai.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',instructions:FX_SYSTEM_PROMPT,input:message});const text=response.output_text?.trim();if(!text)return null;return{intent:'conversation.general',reply:text,confidence:.9,source:'model',reasoning:{needsTool:false}};}catch(error){console.error('[FX OPENAI]',error instanceof Error?error.message:error);return null;}}
export function modelBrainAvailable():boolean{return true;}
export async function planWithModel(message:string):Promise<BrainPlan|null>{const local=await planWithOllama(message);if(local)return local;const cloud=await planWithOpenAI(message);if(cloud)return cloud;return null;}
